parameters:
    installer_bundle.command.database_command.class: 'Akeneo\Platform\Bundle\InstallerBundle\Command\DatabaseCommand'

services:
    akeneo.platform.command.install:
        class: 'Akeneo\Platform\Bundle\InstallerBundle\Command\InstallCommand'
        arguments:
            - '@pim_installer.install_status_manager'
        tags:
            - { name: 'console.command' }
            - { name: 'akeneo.command.authenticated_as_admin_user' }

    Akeneo\Platform\Bundle\InstallerBundle\Command\AssetsCommand:
        arguments:
            - '@filesystem'
            - '@event_dispatcher'
            - '%pim_localization.provider.ui_locale.locale_codes%'
            - '%kernel.project_dir%/src'
        tags:
            - { name: 'console.command' }
            - { name: 'akeneo.command.authenticated_as_admin_user' }

    Akeneo\Platform\Bundle\InstallerBundle\Command\CheckRequirementsCommand:
        tags:
            - { name: console.command }
            - { name: 'akeneo.command.authenticated_as_admin_user' }

    Akeneo\Platform\Bundle\InstallerBundle\Command\DumpRequirePathsCommand:
        arguments:
            - '%kernel.project_dir%/src'
            - '%kernel.bundles%'
        tags:
            - { name: console.command }
            - { name: 'akeneo.command.authenticated_as_admin_user' }

    Akeneo\Platform\Bundle\InstallerBundle\Command\MigrateZddCommand:
        arguments:
            - '@database_connection'
            - '@monolog.logger'
            - !tagged_iterator { tag: 'akeneo.pim.zdd_migration' }
        tags:
            - { name: 'console.command' }
            - { name: 'akeneo.command.authenticated_as_admin_user' }
