services:

  Akeneo\Platform\Installer\Infrastructure\FixtureLoader\JobInstancesBuilder:
    arguments:
      - '@file_locator'
      - '@pim_connector.reader.file.yaml_job_instance'
      - '@pim_installer.processor.denormalization.job_instance'
      - [ 'AkeneoInstallerBundle/Infrastructure/Symfony/Resources/fixtures/fixtures_jobs.yml' ]
